/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.MedicoControlador;
import Controlador.PacienteControlador;
import Modelo.AgendasModelo;
import Modelo.MedicoModelo;
import Modelo.PacienteModelo;
import static Vista.PantallaPrincipal.escritorio;
import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class AgregarMedico extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarMedico
     */
    public AgregarMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        CancelarCita = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        LogoPaciente = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        NombresPaciente = new javax.swing.JLabel();
        numCedula = new javax.swing.JLabel();
        NumCecular = new javax.swing.JLabel();
        TipoSangre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FechaNacimiento = new javax.swing.JLabel();
        Alergias = new javax.swing.JLabel();
        Genero = new javax.swing.JLabel();
        Medicamentos = new javax.swing.JLabel();
        Cargo = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtFechaN = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        CboxCargo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEspecialidad = new javax.swing.JTextArea();
        Masculino = new javax.swing.JCheckBox();
        Femenino = new javax.swing.JCheckBox();
        CheckName = new javax.swing.JLabel();
        CheckAp = new javax.swing.JLabel();
        CheckCed = new javax.swing.JLabel();
        CheckEmail = new javax.swing.JLabel();
        CheckCel1 = new javax.swing.JLabel();
        CheckDic = new javax.swing.JLabel();
        FormatoFecha = new javax.swing.JLabel();
        Administrador = new javax.swing.JLabel();
        FormatoFecha1 = new javax.swing.JLabel();
        txtFechaContratacion = new javax.swing.JTextField();
        CheckFechaN = new javax.swing.JLabel();
        CheckFContratacion = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        ComTipoS = new javax.swing.JComboBox<>();
        txtApellidos1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        CancelarCita.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        CancelarCita.setForeground(new java.awt.Color(48, 44, 44));
        CancelarCita.setText("DATOS PERSONALES");

        btnRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        NombresPaciente.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        NombresPaciente.setText("Nombres Completos    Apellidos Completos");

        numCedula.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        numCedula.setText("N° de Cedula");

        NumCecular.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        NumCecular.setText("N° Celular");

        TipoSangre.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        TipoSangre.setText("Tipo de Sangre");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Correo Electronico");

        FechaNacimiento.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        FechaNacimiento.setText("Fecha de Nacimiento");

        Alergias.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Alergias.setText("Especialidad Medica");

        Genero.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Genero.setText("Genero");

        Medicamentos.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Medicamentos.setText("Fecha de Contratacion");

        Cargo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Cargo.setText("Cargo");

        Direccion.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Direccion.setText("Direccion");

        txtCedula.setBackground(new java.awt.Color(236, 236, 236));
        txtCedula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
        });

        txtCelular.setBackground(new java.awt.Color(236, 236, 236));
        txtCelular.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularKeyPressed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(236, 236, 236));
        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        txtFechaN.setBackground(new java.awt.Color(236, 236, 236));
        txtFechaN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtFechaN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaNKeyPressed(evt);
            }
        });

        txtDireccion.setBackground(new java.awt.Color(236, 236, 236));
        txtDireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });

        txtNombres.setBackground(new java.awt.Color(236, 236, 236));
        txtNombres.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresKeyPressed(evt);
            }
        });

        CboxCargo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CboxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tratante ", "Jefe departamental", " " }));

        txtEspecialidad.setBackground(new java.awt.Color(236, 236, 236));
        txtEspecialidad.setColumns(20);
        txtEspecialidad.setRows(5);
        jScrollPane1.setViewportView(txtEspecialidad);

        Masculino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Masculino.setText("Masculino");

        Femenino.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Femenino.setText("Femenino");

        FormatoFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        FormatoFecha.setForeground(new java.awt.Color(204, 204, 204));
        FormatoFecha.setText("AÑO/MES/DIA");

        Administrador.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Administrador.setForeground(new java.awt.Color(143, 78, 242));
        Administrador.setText("PERSONAL MEDICO");

        FormatoFecha1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        FormatoFecha1.setForeground(new java.awt.Color(204, 204, 204));
        FormatoFecha1.setText("AÑO/MES/DIA");

        txtFechaContratacion.setBackground(new java.awt.Color(236, 236, 236));
        txtFechaContratacion.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtFechaContratacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaContratacionKeyPressed(evt);
            }
        });

        Guardar.setBackground(new java.awt.Color(102, 153, 255));
        Guardar.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 4, true));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        ComTipoS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ComTipoS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "O-", "O+", "AB+", "AB-", "B-", "B+" }));

        txtApellidos1.setBackground(new java.awt.Color(236, 236, 236));
        txtApellidos1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtApellidos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidos1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(CancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127)
                        .addComponent(LogoPaciente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckCed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CheckName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(171, 171, 171))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(NombresPaciente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(CheckAp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(numCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(362, 461, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Masculino)
                                        .addGap(126, 126, 126)
                                        .addComponent(Femenino)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Alergias)
                                            .addGap(90, 90, 90)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NumCecular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Genero)
                                .addGap(138, 138, 138))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(FechaNacimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FormatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ComTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckFContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckDic, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Direccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cargo, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TipoSangre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Medicamentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FormatoFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(394, 394, 394)
                    .addComponent(CheckCel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(901, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(txtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(859, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoPaciente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(CancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Administrador)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alergias, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NombresPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckAp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(numCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckCed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumCecular)
                    .addComponent(Genero))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Masculino)
                    .addComponent(Femenino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoSangre)
                    .addComponent(Medicamentos)
                    .addComponent(FormatoFecha1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CheckFContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Direccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckDic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaNacimiento)
                    .addComponent(FormatoFecha)
                    .addComponent(Cargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar)
                            .addComponent(btnSiguiente)))
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(347, 347, 347)
                    .addComponent(CheckCel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(588, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(txtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(741, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        String user = txtCedula.getText();
        String validarCedula = "^\\d{10}$";

        if (user.matches(validarCedula)) {
            CheckCed.setForeground(Color.GREEN);
            CheckCed.setText("✔");
        } else {
            CheckCed.setForeground(Color.RED);
            CheckCed.setText("✘");
        }

    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyPressed
        String user = txtCelular.getText();
        String validarCelular = "^09\\d{8}$";

        if (user.matches(validarCelular)) {
            CheckCel1.setForeground(Color.GREEN);
            CheckCel1.setText("✔");
        } else {
            CheckCel1.setForeground(Color.RED);
            CheckCel1.setText("✘");
        }
    }//GEN-LAST:event_txtCelularKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        String user = txtEmail.getText();
        String validarEmail = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";

        if (user.matches(validarEmail)) {
            CheckEmail.setForeground(Color.GREEN);
            CheckEmail.setText("✔");
        } else {
            CheckEmail.setForeground(Color.RED);
            CheckEmail.setText("✘");
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtFechaNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaNKeyPressed
        String user = txtFechaN.getText();
        String validarFechaN = "^(?:\\d{4})\\/(?:0[1-9]|1[0-2])\\/(?:0[1-9]|[12][0-9]|3[01])$";

        if (user.matches(validarFechaN)) {
            CheckFechaN.setForeground(Color.GREEN);
            CheckFechaN.setText("✔");
        } else {
            CheckFechaN.setForeground(Color.RED);
            CheckFechaN.setText("✘");
        }
    }//GEN-LAST:event_txtFechaNKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        String user = txtDireccion.getText();
        String validarDireccion = "^[a-zA-Z0-9\\s.,#-]+$";

        if (user.matches(validarDireccion)) {
            CheckDic.setForeground(Color.GREEN);
            CheckDic.setText("✔");
        } else {
            CheckDic.setForeground(Color.RED);
            CheckDic.setText("✘");
        }
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyPressed
        String user = txtNombres.getText();
        String validarApellido = "^[a-z]*[A-Z][a-z]*[A-Z][a-z]*$";

        if (user.matches(validarApellido)) {
            CheckAp.setForeground(Color.GREEN);
            CheckAp.setText("✔");
        } else {
            CheckAp.setForeground(Color.RED);
            CheckAp.setText("✘");
        }

    }//GEN-LAST:event_txtNombresKeyPressed

    private void txtFechaContratacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaContratacionKeyPressed
        String user = txtFechaContratacion.getText();
        String validarFechaC = "^(?:\\d{4})\\/(?:0[1-9]|1[0-2])\\/(?:0[1-9]|[12][0-9]|3[01])$";

        if (user.matches(validarFechaC)) {
            CheckFContratacion.setForeground(Color.GREEN);
            CheckFContratacion.setText("✔");
        } else {
            CheckFContratacion.setForeground(Color.RED);
            CheckFContratacion.setText("✘");
        }
    }//GEN-LAST:event_txtFechaContratacionKeyPressed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
       String genero = (Masculino.isSelected() ? "Masculino" : "Femenino");
       int celular=Integer.parseInt(txtCelular.getText());
       String agenda="1";
       String consultorio="2";
       MedicoModelo mp= new MedicoModelo(0, txtEspecialidad.getText(), CboxCargo.getSelectedItem().toString(), txtFechaContratacion.getText(), null, 
               txtNombres.getText(), txtCedula.getText(),  txtNombres.getText(), txtEmail.getText(), celular, ComTipoS.getSelectedItem().toString(), 
               txtFechaN.getText(), txtDireccion.getText(), genero,agenda,consultorio);
        MedicoControlador pc=new MedicoControlador();
        pc.insertarMedico(mp);
        MenuAdministrador ventanaMP = new MenuAdministrador();
        escritorio.add(ventanaMP);
        ventanaMP.show();
    }//GEN-LAST:event_GuardarActionPerformed

    private void txtApellidos1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidos1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidos1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administrador;
    private javax.swing.JLabel Alergias;
    private javax.swing.JLabel CancelarCita;
    private javax.swing.JLabel Cargo;
    private javax.swing.JComboBox<String> CboxCargo;
    private javax.swing.JLabel CheckAp;
    private javax.swing.JLabel CheckCed;
    private javax.swing.JLabel CheckCel1;
    private javax.swing.JLabel CheckDic;
    private javax.swing.JLabel CheckEmail;
    private javax.swing.JLabel CheckFContratacion;
    private javax.swing.JLabel CheckFechaN;
    private javax.swing.JLabel CheckName;
    private javax.swing.JComboBox<String> ComTipoS;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel FechaNacimiento;
    private javax.swing.JCheckBox Femenino;
    private javax.swing.JLabel FormatoFecha;
    private javax.swing.JLabel FormatoFecha1;
    private javax.swing.JLabel Genero;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LogoPaciente;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JLabel Medicamentos;
    private javax.swing.JLabel NombresPaciente;
    private javax.swing.JLabel NumCecular;
    private javax.swing.JLabel TipoSangre;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numCedula;
    private javax.swing.JTextField txtApellidos1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtEspecialidad;
    private javax.swing.JTextField txtFechaContratacion;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
