/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import static Vista.PantallaPrincipal.escritorio;

/**
 *
 * @author USUARIO
 */
public class CancelarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form CancelarCita
     */
    public CancelarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        CancelarCita = new javax.swing.JLabel();
        paciente = new javax.swing.JLabel();
        TablaHorario = new javax.swing.JPanel();
        Lunes = new javax.swing.JButton();
        Viernes = new javax.swing.JButton();
        Jueves = new javax.swing.JButton();
        Miercoles = new javax.swing.JButton();
        Martes = new javax.swing.JButton();
        Lunes6 = new javax.swing.JButton();
        Lunes5 = new javax.swing.JButton();
        Lunes4 = new javax.swing.JButton();
        Lunes3 = new javax.swing.JButton();
        Lunes2 = new javax.swing.JButton();
        Lunes1 = new javax.swing.JButton();
        Horario6 = new javax.swing.JButton();
        Horario5 = new javax.swing.JButton();
        Horario4 = new javax.swing.JButton();
        Horario3 = new javax.swing.JButton();
        Horario2 = new javax.swing.JButton();
        Horario1 = new javax.swing.JButton();
        Horario = new javax.swing.JButton();
        Martes1 = new javax.swing.JButton();
        Miercoles1 = new javax.swing.JButton();
        Jueves1 = new javax.swing.JButton();
        Viernes1 = new javax.swing.JButton();
        Martes2 = new javax.swing.JButton();
        Miercoles2 = new javax.swing.JButton();
        Jueves2 = new javax.swing.JButton();
        Viernes2 = new javax.swing.JButton();
        Martes3 = new javax.swing.JButton();
        Miercoles3 = new javax.swing.JButton();
        Jueves3 = new javax.swing.JButton();
        Viernes3 = new javax.swing.JButton();
        Martes4 = new javax.swing.JButton();
        Miercoles4 = new javax.swing.JButton();
        Jueves4 = new javax.swing.JButton();
        Viernes4 = new javax.swing.JButton();
        Martes5 = new javax.swing.JButton();
        Miercoles5 = new javax.swing.JButton();
        Jueves5 = new javax.swing.JButton();
        Viernes5 = new javax.swing.JButton();
        Martes6 = new javax.swing.JButton();
        Miercoles6 = new javax.swing.JButton();
        Jueves6 = new javax.swing.JButton();
        Viernes6 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        LogoPaciente = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        lblCedula1 = new javax.swing.JLabel();
        TablaInfoCita = new javax.swing.JPanel();
        FechaCita = new javax.swing.JButton();
        EstadoCita = new javax.swing.JButton();
        Especialidad = new javax.swing.JButton();
        NombreDoctor = new javax.swing.JButton();
        NumConsultorio = new javax.swing.JButton();
        NumPiso = new javax.swing.JButton();
        lblNumPiso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNumPiso1 = new javax.swing.JLabel();
        lblNumPiso2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        CancelarCita.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        CancelarCita.setForeground(new java.awt.Color(48, 44, 44));
        CancelarCita.setText("CANCELAR CITA");

        paciente.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        paciente.setForeground(new java.awt.Color(51, 153, 255));
        paciente.setText("PACIENTE");

        TablaHorario.setBackground(new java.awt.Color(250, 250, 250));

        Lunes.setBackground(new java.awt.Color(0, 102, 102));
        Lunes.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes.setForeground(new java.awt.Color(255, 255, 255));
        Lunes.setText("Lunes");
        Lunes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes.setBackground(new java.awt.Color(0, 102, 102));
        Viernes.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes.setForeground(new java.awt.Color(255, 255, 255));
        Viernes.setText("Viernes");
        Viernes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves.setBackground(new java.awt.Color(0, 102, 102));
        Jueves.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves.setForeground(new java.awt.Color(255, 255, 255));
        Jueves.setText("Jueves");
        Jueves.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles.setBackground(new java.awt.Color(0, 102, 102));
        Miercoles.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles.setText("Miercoles");
        Miercoles.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes.setBackground(new java.awt.Color(0, 102, 102));
        Martes.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes.setForeground(new java.awt.Color(255, 255, 255));
        Martes.setText("Martes");
        Martes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lunes6.setBackground(new java.awt.Color(204, 204, 204));
        Lunes6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes6.setForeground(new java.awt.Color(255, 255, 255));
        Lunes6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lunes5.setBackground(new java.awt.Color(204, 204, 204));
        Lunes5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes5.setForeground(new java.awt.Color(255, 255, 255));
        Lunes5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lunes4.setBackground(new java.awt.Color(204, 204, 204));
        Lunes4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes4.setForeground(new java.awt.Color(255, 255, 255));
        Lunes4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lunes3.setBackground(new java.awt.Color(204, 204, 204));
        Lunes3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes3.setForeground(new java.awt.Color(255, 255, 255));
        Lunes3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lunes2.setBackground(new java.awt.Color(204, 204, 204));
        Lunes2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes2.setForeground(new java.awt.Color(255, 255, 255));
        Lunes2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Lunes1.setBackground(new java.awt.Color(204, 204, 204));
        Lunes1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lunes1.setForeground(new java.awt.Color(255, 255, 255));
        Lunes1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario6.setBackground(new java.awt.Color(0, 102, 102));
        Horario6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Horario6.setForeground(new java.awt.Color(255, 255, 255));
        Horario6.setText("13:00 - 14:00");
        Horario6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario5.setBackground(new java.awt.Color(0, 102, 102));
        Horario5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Horario5.setForeground(new java.awt.Color(255, 255, 255));
        Horario5.setText("12:00 - 13:00");
        Horario5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario4.setBackground(new java.awt.Color(0, 102, 102));
        Horario4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Horario4.setForeground(new java.awt.Color(255, 255, 255));
        Horario4.setText("11:00 - 12:00");
        Horario4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario3.setBackground(new java.awt.Color(0, 102, 102));
        Horario3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Horario3.setForeground(new java.awt.Color(255, 255, 255));
        Horario3.setText("10:00 - 11:00");
        Horario3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario2.setBackground(new java.awt.Color(0, 102, 102));
        Horario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Horario2.setForeground(new java.awt.Color(255, 255, 255));
        Horario2.setText("9:00 - 10:00");
        Horario2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario1.setBackground(new java.awt.Color(0, 102, 102));
        Horario1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Horario1.setForeground(new java.awt.Color(255, 255, 255));
        Horario1.setText("8:00 - 9:00");
        Horario1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Horario.setBackground(new java.awt.Color(0, 102, 102));
        Horario.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        Horario.setForeground(new java.awt.Color(255, 255, 255));
        Horario.setText("Horario");
        Horario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes1.setBackground(new java.awt.Color(204, 204, 204));
        Martes1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes1.setForeground(new java.awt.Color(255, 255, 255));
        Martes1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles1.setBackground(new java.awt.Color(204, 204, 204));
        Miercoles1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles1.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves1.setBackground(new java.awt.Color(204, 204, 204));
        Jueves1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves1.setForeground(new java.awt.Color(255, 255, 255));
        Jueves1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes1.setBackground(new java.awt.Color(204, 204, 204));
        Viernes1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes1.setForeground(new java.awt.Color(255, 255, 255));
        Viernes1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes2.setBackground(new java.awt.Color(204, 204, 204));
        Martes2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes2.setForeground(new java.awt.Color(255, 255, 255));
        Martes2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles2.setBackground(new java.awt.Color(204, 204, 204));
        Miercoles2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles2.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves2.setBackground(new java.awt.Color(204, 204, 204));
        Jueves2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves2.setForeground(new java.awt.Color(255, 255, 255));
        Jueves2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes2.setBackground(new java.awt.Color(204, 204, 204));
        Viernes2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes2.setForeground(new java.awt.Color(255, 255, 255));
        Viernes2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes3.setBackground(new java.awt.Color(204, 204, 204));
        Martes3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes3.setForeground(new java.awt.Color(255, 255, 255));
        Martes3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles3.setBackground(new java.awt.Color(204, 204, 204));
        Miercoles3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles3.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves3.setBackground(new java.awt.Color(204, 204, 204));
        Jueves3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves3.setForeground(new java.awt.Color(255, 255, 255));
        Jueves3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes3.setBackground(new java.awt.Color(204, 204, 204));
        Viernes3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes3.setForeground(new java.awt.Color(255, 255, 255));
        Viernes3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes4.setBackground(new java.awt.Color(204, 204, 204));
        Martes4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes4.setForeground(new java.awt.Color(255, 255, 255));
        Martes4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles4.setBackground(new java.awt.Color(204, 204, 204));
        Miercoles4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles4.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves4.setBackground(new java.awt.Color(204, 204, 204));
        Jueves4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves4.setForeground(new java.awt.Color(255, 255, 255));
        Jueves4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes4.setBackground(new java.awt.Color(204, 204, 204));
        Viernes4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes4.setForeground(new java.awt.Color(255, 255, 255));
        Viernes4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes5.setBackground(new java.awt.Color(204, 204, 204));
        Martes5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes5.setForeground(new java.awt.Color(255, 255, 255));
        Martes5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles5.setBackground(new java.awt.Color(204, 204, 204));
        Miercoles5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles5.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves5.setBackground(new java.awt.Color(204, 204, 204));
        Jueves5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves5.setForeground(new java.awt.Color(255, 255, 255));
        Jueves5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes5.setBackground(new java.awt.Color(204, 204, 204));
        Viernes5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes5.setForeground(new java.awt.Color(255, 255, 255));
        Viernes5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Martes6.setBackground(new java.awt.Color(204, 204, 204));
        Martes6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Martes6.setForeground(new java.awt.Color(255, 255, 255));
        Martes6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Miercoles6.setBackground(new java.awt.Color(204, 204, 204));
        Miercoles6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Miercoles6.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Jueves6.setBackground(new java.awt.Color(204, 204, 204));
        Jueves6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Jueves6.setForeground(new java.awt.Color(255, 255, 255));
        Jueves6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Viernes6.setBackground(new java.awt.Color(204, 204, 204));
        Viernes6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Viernes6.setForeground(new java.awt.Color(255, 255, 255));
        Viernes6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout TablaHorarioLayout = new javax.swing.GroupLayout(TablaHorario);
        TablaHorario.setLayout(TablaHorarioLayout);
        TablaHorarioLayout.setHorizontalGroup(
            TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaHorarioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Horario2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Horario1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lunes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lunes1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Lunes2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addComponent(Horario3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lunes3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(TablaHorarioLayout.createSequentialGroup()
                            .addComponent(Horario4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lunes4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Horario5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lunes5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Horario6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lunes6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Martes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Martes1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Martes2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Miercoles2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(Jueves2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(Viernes2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Martes3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Miercoles3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(Jueves3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(Viernes3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Martes4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Miercoles4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(Jueves4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(Viernes4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Martes5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Miercoles5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(Jueves5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(Viernes5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Martes6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Miercoles6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(Jueves6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(Viernes6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        TablaHorarioLayout.setVerticalGroup(
            TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaHorarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Martes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Viernes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jueves, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lunes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Miercoles1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Miercoles6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Jueves1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jueves6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addComponent(Viernes1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Viernes6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaHorarioLayout.createSequentialGroup()
                        .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Martes1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lunes1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Martes2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lunes2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addComponent(Horario1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Horario2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addComponent(Martes3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Martes4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(TablaHorarioLayout.createSequentialGroup()
                                    .addComponent(Lunes3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lunes4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TablaHorarioLayout.createSequentialGroup()
                                    .addComponent(Horario3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Horario4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addComponent(Martes5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Martes6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TablaHorarioLayout.createSequentialGroup()
                                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lunes5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Horario5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(TablaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lunes6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Horario6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblNombre.setText("Nombre del Paciente");

        lblCedula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCedula.setText("Numero de Cedula");

        LogoPaciente.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\MediMeetup\\src\\main\\resource\\Imagenes\\90.Paciente.jpg")); // NOI18N

        btnRegresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\MediMeetup\\src\\main\\resource\\Imagenes\\48.FlechaR.png")); // NOI18N
        btnRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\MediMeetup\\src\\main\\resource\\Imagenes\\48.FlechaV.png")); // NOI18N
        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblCedula1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        TablaInfoCita.setBackground(new java.awt.Color(250, 250, 250));

        FechaCita.setBackground(new java.awt.Color(0, 102, 102));
        FechaCita.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        FechaCita.setForeground(new java.awt.Color(255, 255, 255));
        FechaCita.setText("Fecha Cita");
        FechaCita.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        EstadoCita.setBackground(new java.awt.Color(0, 102, 102));
        EstadoCita.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        EstadoCita.setForeground(new java.awt.Color(255, 255, 255));
        EstadoCita.setText("Estado Cita");
        EstadoCita.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Especialidad.setBackground(new java.awt.Color(0, 102, 102));
        Especialidad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Especialidad.setForeground(new java.awt.Color(255, 255, 255));
        Especialidad.setText("Especialidad Medica");
        Especialidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadActionPerformed(evt);
            }
        });

        NombreDoctor.setBackground(new java.awt.Color(0, 102, 102));
        NombreDoctor.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NombreDoctor.setForeground(new java.awt.Color(255, 255, 255));
        NombreDoctor.setText("Nombre Doctor");
        NombreDoctor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        NumConsultorio.setBackground(new java.awt.Color(0, 102, 102));
        NumConsultorio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NumConsultorio.setForeground(new java.awt.Color(255, 255, 255));
        NumConsultorio.setText("N° Consultorio");
        NumConsultorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        NumPiso.setBackground(new java.awt.Color(0, 102, 102));
        NumPiso.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        NumPiso.setForeground(new java.awt.Color(255, 255, 255));
        NumPiso.setText("N° de Piso");
        NumPiso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblNumPiso.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblNumPiso.setForeground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));

        lblNumPiso1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblNumPiso1.setForeground(new java.awt.Color(0, 102, 153));

        lblNumPiso2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblNumPiso2.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout TablaInfoCitaLayout = new javax.swing.GroupLayout(TablaInfoCita);
        TablaInfoCita.setLayout(TablaInfoCitaLayout);
        TablaInfoCitaLayout.setHorizontalGroup(
            TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Especialidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EstadoCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablaInfoCitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumConsultorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreDoctor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumPiso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumPiso1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumPiso2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        TablaInfoCitaLayout.setVerticalGroup(
            TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumPiso, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                                .addComponent(lblNumPiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                                .addComponent(NumConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Especialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstadoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(TablaInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TablaInfoCitaLayout.createSequentialGroup()
                        .addComponent(lblNumPiso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addComponent(FechaCita, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(241, 241, 241))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(CancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(LogoPaciente)
                                        .addGap(180, 180, 180)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(342, 342, 342)
                                        .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(563, 563, 563)
                                        .addComponent(lblCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TablaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TablaInfoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoPaciente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TablaInfoCita, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(btnSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPaciente ventanaMP = new MenuPaciente();
        escritorio.add(ventanaMP);
        ventanaMP.show();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        MenuPaciente ventanaMP = new MenuPaciente();
        escritorio.add(ventanaMP);
        ventanaMP.show();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CancelarCita;
    private javax.swing.JButton Especialidad;
    private javax.swing.JButton EstadoCita;
    private javax.swing.JButton FechaCita;
    private javax.swing.JButton Horario;
    private javax.swing.JButton Horario1;
    private javax.swing.JButton Horario2;
    private javax.swing.JButton Horario3;
    private javax.swing.JButton Horario4;
    private javax.swing.JButton Horario5;
    private javax.swing.JButton Horario6;
    private javax.swing.JButton Jueves;
    private javax.swing.JButton Jueves1;
    private javax.swing.JButton Jueves2;
    private javax.swing.JButton Jueves3;
    private javax.swing.JButton Jueves4;
    private javax.swing.JButton Jueves5;
    private javax.swing.JButton Jueves6;
    private javax.swing.JLabel LogoPaciente;
    private javax.swing.JButton Lunes;
    private javax.swing.JButton Lunes1;
    private javax.swing.JButton Lunes2;
    private javax.swing.JButton Lunes3;
    private javax.swing.JButton Lunes4;
    private javax.swing.JButton Lunes5;
    private javax.swing.JButton Lunes6;
    private javax.swing.JButton Martes;
    private javax.swing.JButton Martes1;
    private javax.swing.JButton Martes2;
    private javax.swing.JButton Martes3;
    private javax.swing.JButton Martes4;
    private javax.swing.JButton Martes5;
    private javax.swing.JButton Martes6;
    private javax.swing.JButton Miercoles;
    private javax.swing.JButton Miercoles1;
    private javax.swing.JButton Miercoles2;
    private javax.swing.JButton Miercoles3;
    private javax.swing.JButton Miercoles4;
    private javax.swing.JButton Miercoles5;
    private javax.swing.JButton Miercoles6;
    private javax.swing.JButton NombreDoctor;
    private javax.swing.JButton NumConsultorio;
    private javax.swing.JButton NumPiso;
    private javax.swing.JPanel TablaHorario;
    private javax.swing.JPanel TablaInfoCita;
    private javax.swing.JButton Viernes;
    private javax.swing.JButton Viernes1;
    private javax.swing.JButton Viernes2;
    private javax.swing.JButton Viernes3;
    private javax.swing.JButton Viernes4;
    private javax.swing.JButton Viernes5;
    private javax.swing.JButton Viernes6;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNumPiso;
    private javax.swing.JLabel lblNumPiso1;
    private javax.swing.JLabel lblNumPiso2;
    private javax.swing.JLabel paciente;
    // End of variables declaration//GEN-END:variables
}
