/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CitasControlador;
import Controlador.MedicoControlador;
import Controlador.PacienteControlador;
import Modelo.CitasModelo;
import Modelo.MedicoModelo;
import Modelo.PacienteModelo;
import static Vista.PantallaPrincipal.escritorio;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class ReagendarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReagendarCita
     */
    public ReagendarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        paciente1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        LogoPaciente1 = new javax.swing.JLabel();
        EspecialidadMedica = new javax.swing.JLabel();
        CBoxEspecialidad = new javax.swing.JComboBox<>();
        ConfirmarAgenda = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        btnSiguiente1 = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        Hora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        EspecialidadMedica2 = new javax.swing.JLabel();
        Hora1 = new javax.swing.JLabel();
        ReagendarCita = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);

        paciente1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        paciente1.setForeground(new java.awt.Color(51, 153, 255));
        paciente1.setText("PACIENTE");

        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblCedula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        EspecialidadMedica.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        EspecialidadMedica.setText("Especialidad Medica");

        CBoxEspecialidad.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neurologia", "Pediatria", "Medicina General", "Cardiologia", "Medicina Interna", "Ginecologia", "Psiquiatria" }));

        ConfirmarAgenda.setBackground(new java.awt.Color(102, 153, 255));
        ConfirmarAgenda.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        ConfirmarAgenda.setText("Reagendar");
        ConfirmarAgenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 4, true));
        ConfirmarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAgendaActionPerformed(evt);
            }
        });

        btnRegresar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        btnSiguiente1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente1ActionPerformed(evt);
            }
        });

        Hora.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Hora.setText("Hora");

        EspecialidadMedica2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        EspecialidadMedica2.setText("Cedula Paciente");

        Hora1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Hora1.setText("Fecha");

        ReagendarCita.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ReagendarCita.setForeground(new java.awt.Color(48, 44, 44));
        ReagendarCita.setText("REAGENDAR CITA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addComponent(LogoPaciente1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hora)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EspecialidadMedica)
                                        .addComponent(CBoxEspecialidad, 0, 231, Short.MAX_VALUE)
                                        .addComponent(txtHora)
                                        .addComponent(txtDia)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ReagendarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Hora1))))
                        .addGap(180, 180, 180)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(ConfirmarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(EspecialidadMedica2)
                    .addContainerGap(723, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ReagendarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EspecialidadMedica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(Hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hora1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LogoPaciente1))
                .addGap(43, 43, 43)
                .addComponent(ConfirmarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar1)
                    .addComponent(btnSiguiente1))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(EspecialidadMedica2)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAgendaActionPerformed
        CitasControlador citasControlador = new CitasControlador();
        PacienteControlador pacienteControlador = new PacienteControlador();
        MedicoControlador medicoControlador = new MedicoControlador();
        String cedula = txtCedula.getText();
        String hora = txtHora.getText();
        String dia = txtDia.getText();
        String especialidad = CBoxEspecialidad.getSelectedItem().toString();
        PacienteModelo pacienteModelo = new PacienteModelo();
        // Establecer la cédula del paciente en el modelo
        pacienteModelo.setCedula(cedula);
        MedicoModelo medico= new MedicoModelo(especialidad);
        CitasModelo citaModelo = new CitasModelo(0, cedula, hora, dia, especialidad);
        citasControlador.IngresarCitaReprogramada(citaModelo, pacienteModelo, medico);
        JOptionPane.showMessageDialog(null, "Cita reagendada con éxito");
        //
        MenuPaciente ventanaMP = new MenuPaciente();
        escritorio.add(ventanaMP);
        ventanaMP.show();
    }//GEN-LAST:event_ConfirmarAgendaActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSiguiente1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxEspecialidad;
    private javax.swing.JButton ConfirmarAgenda;
    private javax.swing.JLabel EspecialidadMedica;
    private javax.swing.JLabel EspecialidadMedica2;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Hora1;
    private javax.swing.JLabel LogoPaciente1;
    private javax.swing.JLabel ReagendarCita;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnSiguiente1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel paciente1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
