/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.UsuariosControlador;
import Modelo.UsuarioModelo;
import static Vista.PantallaPrincipal.escritorio;
import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class RecuperarClaveAdmi extends javax.swing.JInternalFrame {

    /**
     * Creates new form RecuperarClave
     */
    public RecuperarClaveAdmi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ultimosDigitosCedula = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btnObtenerClave = new javax.swing.JButton();
        PrimerasLetrasNombre = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        preguntaS = new javax.swing.JLabel();
        nuevacontraseña = new javax.swing.JTextField();
        nuevaCla = new javax.swing.JLabel();
        txtpregunta = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 241, 241));
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ultimosDigitosCedula.setBackground(new java.awt.Color(236, 236, 236));

        Titulo.setBackground(new java.awt.Color(255, 153, 51));
        Titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 153, 0));
        Titulo.setText("Responder la pregunta de Seguridad");

        btnObtenerClave.setBackground(new java.awt.Color(0, 153, 153));
        btnObtenerClave.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnObtenerClave.setForeground(new java.awt.Color(255, 255, 255));
        btnObtenerClave.setText("Guardar Contraseña!!");
        btnObtenerClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerClaveActionPerformed(evt);
            }
        });

        PrimerasLetrasNombre.setText("Usuario");

        txtusuario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusuarioKeyPressed(evt);
            }
        });

        preguntaS.setText("Pregunta de seguridad");

        nuevacontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nuevacontraseñaKeyPressed(evt);
            }
        });

        nuevaCla.setText("Nueva Clave");

        txtpregunta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpreguntaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout ultimosDigitosCedulaLayout = new javax.swing.GroupLayout(ultimosDigitosCedula);
        ultimosDigitosCedula.setLayout(ultimosDigitosCedulaLayout);
        ultimosDigitosCedulaLayout.setHorizontalGroup(
            ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ultimosDigitosCedulaLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ultimosDigitosCedulaLayout.createSequentialGroup()
                        .addGroup(ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo)
                            .addGroup(ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ultimosDigitosCedulaLayout.createSequentialGroup()
                                    .addComponent(preguntaS, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtpregunta))
                                .addGroup(ultimosDigitosCedulaLayout.createSequentialGroup()
                                    .addComponent(PrimerasLetrasNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ultimosDigitosCedulaLayout.createSequentialGroup()
                                .addComponent(nuevaCla, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevacontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ultimosDigitosCedulaLayout.createSequentialGroup()
                        .addComponent(btnObtenerClave)
                        .addGap(128, 128, 128))))
        );
        ultimosDigitosCedulaLayout.setVerticalGroup(
            ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ultimosDigitosCedulaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Titulo)
                .addGap(46, 46, 46)
                .addGroup(ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerasLetrasNombre)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preguntaS)
                    .addComponent(txtpregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ultimosDigitosCedulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaCla)
                    .addComponent(nuevacontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnObtenerClave)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        btnSiguiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ultimosDigitosCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ultimosDigitosCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguiente)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerClaveActionPerformed
        
        //ENVIAR UN MENSAJE CON LA CONTRASEÑA
        UsuarioModelo usuario=new UsuarioModelo(txtusuario.getText(), nuevacontraseña.getText(), 
                txtpregunta.getText());
        UsuariosControlador usuariocon=new UsuariosControlador();
        usuariocon.actualizarUsuario(usuario);
        MenuAdministrador ventanaMM = new MenuAdministrador();
        escritorio.add(ventanaMM);
        ventanaMM.show();
    }//GEN-LAST:event_btnObtenerClaveActionPerformed

    private void txtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyPressed
        String nombre = txtusuario.getText();
    
    String usuario = "^[0-9][9]+$";
    
        if (nombre.matches(usuario)) {
            PrimerasLetrasNombre.setForeground(Color.GREEN);
        } else {
            PrimerasLetrasNombre.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtusuarioKeyPressed

    private void nuevacontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevacontraseñaKeyPressed
        String cedula = nuevacontraseña.getText();
    
    String validarCedula = "^[A-Z][a-z]+$";
    
        if (cedula.matches(validarCedula)) {
            ultimosDigitosCedula.setForeground(Color.GREEN);
        } else {
            ultimosDigitosCedula.setForeground(Color.RED);
        }
    }//GEN-LAST:event_nuevacontraseñaKeyPressed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        MenuAdministrador ventanaMM = new MenuAdministrador();
        escritorio.add(ventanaMM);
        ventanaMM.show();
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtpreguntaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreguntaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreguntaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrimerasLetrasNombre;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnObtenerClave;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nuevaCla;
    private javax.swing.JTextField nuevacontraseña;
    private javax.swing.JLabel preguntaS;
    private javax.swing.JTextField txtpregunta;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JPanel ultimosDigitosCedula;
    // End of variables declaration//GEN-END:variables
}
